[package]
name = "shelltranspiler"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.3.0"
chumsky = { version = "1.0.0-alpha.6", features = ["label"] }
clap = { version = "4.4.8", features = ["derive"] }
